### ISSUE TITLE
Got following output after following installation instructions (Error: spawn ENOENT)

### ISSUE THREAD

**Issue by andruhon** [TravelingTechGuy/Meny.docpad#1]
info: Welcome to DocPad v6.54.5 (local installation: D:\Dev\docpad_test\Meny.docpad\node_modules\docpad)
info: Contribute: http://docpad.org/docs/contribute
info: Plugins: coffeescript, eco, marked, partials, stylus, text
info: Environment: development
info: DocPad listening to http://localhost:9778/ on directory D:\Dev\docpad_test\Meny.docpad\out
info: Generating...
error: Something went wrong with the action
error: An error occured:
Error: spawn ENOENT
    at errnoException (child_process.js:977:11)
    at Process.ChildProcess._handle.onexit (child_process.js:768:34)
info: Shutting down... cya next time!

**Comment by TravelingTechGuy** [comment]
@andruhon can you please post the entire command you typed, and at which step did this occur? I have not tested on Windows, but I don't see an immediate reason for this failure.

**Comment by andruhon** [comment]
D:\Dev\docpad_test>git clone git://github.com/TravelingTechGuy/Meny.docpad.git
Cloning into 'Meny.docpad'...
remote: Counting objects: 272, done.
remote: Compressing objects: 100% (166/166), done.
remote: Total 272 (delta 111), reused 247 (delta 86)R
Receiving objects:  87% (237/272), 172.00 KiB | 103.00 KiB/s
Receiving objects: 100% (272/272), 234.35 KiB | 103.00 KiB/s, done.
Resolving deltas: 100% (111/111), done.

D:\Dev\docpad_test>cd Meny.docpad\

D:\Dev\docpad_test\Meny.docpad>npm install
npm http GET https://registry.npmjs.org/docpad-plugin-eco
npm http GET https://registry.npmjs.org/docpad-plugin-text
npm http GET https://registry.npmjs.org/docpad-plugin-coffeescript
npm http GET https://registry.npmjs.org/docpad-plugin-stylus
npm http GET https://registry.npmjs.org/docpad-plugin-marked
npm http GET https://registry.npmjs.org/grunt
npm http GET https://registry.npmjs.org/grunt-css
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/docpad-plugin-partials
npm http GET https://registry.npmjs.org/bal-util
npm http GET https://registry.npmjs.org/docpad
npm http 304 https://registry.npmjs.org/docpad-plugin-coffeescript
npm http 304 https://registry.npmjs.org/docpad-plugin-stylus
npm http 304 https://registry.npmjs.org/docpad-plugin-marked
npm http 304 https://registry.npmjs.org/docpad-plugin-eco
npm http 304 https://registry.npmjs.org/docpad-plugin-text
npm http 304 https://registry.npmjs.org/grunt
npm http 304 https://registry.npmjs.org/grunt-css
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/docpad-plugin-partials
npm http 304 https://registry.npmjs.org/bal-util
npm http 304 https://registry.npmjs.org/docpad
npm http GET https://registry.npmjs.org/eco
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/nib
npm http GET https://registry.npmjs.org/stylus
npm http GET https://registry.npmjs.org/taskgroup
npm http GET https://registry.npmjs.org/marked
npm http GET https://registry.npmjs.org/sqwish/0.2.0
npm http GET https://registry.npmjs.org/gzip-js/0.3.1
npm http GET https://registry.npmjs.org/csslint/0.9.9
npm http GET https://registry.npmjs.org/extendr
npm http GET https://registry.npmjs.org/backbone/1.1.0
npm http GET https://registry.npmjs.org/caterpillar-filter
npm http GET https://registry.npmjs.org/ambi
npm http GET https://registry.npmjs.org/cson
npm http GET https://registry.npmjs.org/caterpillar
npm http GET https://registry.npmjs.org/eachr
npm http GET https://registry.npmjs.org/caterpillar-human
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/lazy-require
npm http GET https://registry.npmjs.org/encoding
npm http GET https://registry.npmjs.org/event-emitter-grouped
npm http GET https://registry.npmjs.org/extract-opts
npm http GET https://registry.npmjs.org/safeps
npm http GET https://registry.npmjs.org/superagent
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/jschardet
npm http GET https://registry.npmjs.org/safefs
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/query-engine
npm http GET https://registry.npmjs.org/watchr
npm http GET https://registry.npmjs.org/yamljs
npm http GET https://registry.npmjs.org/progressbar
npm http GET https://registry.npmjs.org/envfile
npm http GET https://registry.npmjs.org/promptly
npm http GET https://registry.npmjs.org/getmac
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/typechecker
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/connect
npm http GET https://registry.npmjs.org/glob-whatev
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/dateformat/1.0.2-1.2.3
npm http GET https://registry.npmjs.org/hooker
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/jshint
npm http GET https://registry.npmjs.org/nodeunit
npm http GET https://registry.npmjs.org/prompt
npm http GET https://registry.npmjs.org/underscore.string
npm http GET https://registry.npmjs.org/gzip-js
npm http GET https://registry.npmjs.org/temporary
npm http GET https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/coffee-script
npm http 304 https://registry.npmjs.org/stylus
npm http 304 https://registry.npmjs.org/eco
npm http 304 https://registry.npmjs.org/nib
npm http 304 https://registry.npmjs.org/taskgroup

> taskgroup@3.3.1 preinstall D:\Dev\docpad_test\Meny.docpad\node_modules\docpad-
> plugin-text\node_modules\taskgroup
> node ./cyclic.js

npm http GET https://registry.npmjs.org/safefs
npm http GET https://registry.npmjs.org/strscan
npm http 304 https://registry.npmjs.org/marked
npm http 304 https://registry.npmjs.org/sqwish/0.2.0
npm http 304 https://registry.npmjs.org/csslint/0.9.9
npm http 304 https://registry.npmjs.org/gzip-js/0.3.1
npm http GET https://registry.npmjs.org/ambi
npm http 304 https://registry.npmjs.org/extendr
npm http GET https://registry.npmjs.org/typechecker

> taskgroup@3.3.1 preinstall D:\Dev\docpad_test\Meny.docpad\node_modules\docpad-
> plugin-partials\node_modules\taskgroup
> node ./cyclic.js

npm http GET https://registry.npmjs.org/crc32
npm http GET https://registry.npmjs.org/deflate-js
npm http GET https://registry.npmjs.org/cssom
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/backbone/1.1.0
npm http GET https://registry.npmjs.org/sax
npm http 304 https://registry.npmjs.org/caterpillar-filter
npm http 304 https://registry.npmjs.org/ambi
npm http 304 https://registry.npmjs.org/cson
npm http 304 https://registry.npmjs.org/caterpillar
npm http 304 https://registry.npmjs.org/eachr
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/caterpillar-human
npm http 304 https://registry.npmjs.org/lazy-require
npm http 304 https://registry.npmjs.org/encoding
npm http 304 https://registry.npmjs.org/event-emitter-grouped
npm http 304 https://registry.npmjs.org/extract-opts
npm http 304 https://registry.npmjs.org/safeps
npm http 304 https://registry.npmjs.org/superagent
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/jschardet
npm http 304 https://registry.npmjs.org/safefs
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/query-engine
npm http 304 https://registry.npmjs.org/watchr
npm http 304 https://registry.npmjs.org/yamljs
npm http 304 https://registry.npmjs.org/progressbar
npm http 304 https://registry.npmjs.org/envfile
npm http 304 https://registry.npmjs.org/promptly
npm http 304 https://registry.npmjs.org/getmac
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/typechecker
npm http 304 https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/colors
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/connect
npm http 304 https://registry.npmjs.org/glob-whatev
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/dateformat/1.0.2-1.2.3
npm http 304 https://registry.npmjs.org/hooker
npm http GET https://registry.npmjs.org/iconv-lite
npm http GET https://registry.npmjs.org/ansistyles
npm http GET https://registry.npmjs.org/ansicolors
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/progress/1.1.2

> ambi@2.1.6 preinstall D:\Dev\docpad_test\Meny.docpad\node_modules\docpad\node_
> modules\ambi
> node ./cyclic.js

npm http GET https://registry.npmjs.org/read

> typechecker@2.0.8 preinstall D:\Dev\docpad_test\Meny.docpad\node_modules\docpa
> d\node_modules\typechecker
> node ./cyclic.js
> 
> safefs@3.0.4 preinstall D:\Dev\docpad_test\Meny.docpad\node_modules\docpad\nod
> e_modules\safefs
> node ./cyclic.js
> 
> cson@1.4.5 preinstall D:\Dev\docpad_test\Meny.docpad\node_modules\docpad\node_
> modules\cson
> node ./cyclic.js

npm http 304 https://registry.npmjs.org/nopt
npm http 304 https://registry.npmjs.org/jshint
npm http 304 https://registry.npmjs.org/nodeunit

> taskgroup@3.3.1 preinstall D:\Dev\docpad_test\Meny.docpad\node_modules\docpad\
> node_modules\taskgroup
> node ./cyclic.js
> 
> safeps@2.2.9 preinstall D:\Dev\docpad_test\Meny.docpad\node_modules\docpad\nod
> e_modules\safeps
> node ./cyclic.js

npm http 304 https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/prompt
npm http GET https://registry.npmjs.org/requirefresh
npm http GET https://registry.npmjs.org/js2coffee

> taskgroup@3.2.4 preinstall D:\Dev\docpad_test\Meny.docpad\node_modules\docpad\
> node_modules\watchr\node_modules\taskgroup
> node ./cyclic.js

npm http 304 https://registry.npmjs.org/gzip-js
npm http 304 https://registry.npmjs.org/temporary
npm http 304 https://registry.npmjs.org/uglify-js
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/methods/0.0.1
npm http GET https://registry.npmjs.org/cookiejar/1.3.0
npm http GET https://registry.npmjs.org/commander/1.3.2
npm http GET https://registry.npmjs.org/mkdirp/0.3.5
npm http GET https://registry.npmjs.org/range-parser/0.0.4
npm http GET https://registry.npmjs.org/mime/1.2.5
npm http GET https://registry.npmjs.org/emitter-component/1.0.0
npm http GET https://registry.npmjs.org/connect/2.11.0
npm http GET https://registry.npmjs.org/cookie-signature/1.0.1
npm http GET https://registry.npmjs.org/qs/0.6.5
npm http GET https://registry.npmjs.org/reduce-component/1.0.1
npm http GET https://registry.npmjs.org/buffer-crc32/0.2.1
npm http GET https://registry.npmjs.org/fresh/0.2.0
npm http GET https://registry.npmjs.org/cookie/0.1.0
npm http GET https://registry.npmjs.org/methods/0.1.0
npm http GET https://registry.npmjs.org/send/0.1.4
npm http GET https://registry.npmjs.org/formidable/1.0.14
npm http 304 https://registry.npmjs.org/strscan
npm http 304 https://registry.npmjs.org/typechecker
npm http 304 https://registry.npmjs.org/ambi
npm http 304 https://registry.npmjs.org/crc32
npm http GET https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/argparse
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/deflate-js
npm http GET https://registry.npmjs.org/package

> ambi@2.1.6 preinstall D:\Dev\docpad_test\Meny.docpad\node_modules\docpad-plugi
> n-text\node_modules\taskgroup\node_modules\ambi
> node ./cyclic.js
> 
> typechecker@2.0.8 preinstall D:\Dev\docpad_test\Meny.docpad\node_modules\docpa
> d-plugin-partials\node_modules\extendr\node_modules\typechecker
> node ./cyclic.js

npm http 304 https://registry.npmjs.org/cssom
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/pkginfo
npm http GET https://registry.npmjs.org/winston
npm http 304 https://registry.npmjs.org/sax
npm http 304 https://registry.npmjs.org/safefs
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/cli/0.4.3
npm http 304 https://registry.npmjs.org/iconv-lite

> ambi@2.1.6 preinstall D:\Dev\docpad_test\Meny.docpad\node_modules\docpad-plugi
> n-partials\node_modules\taskgroup\node_modules\ambi
> node ./cyclic.js
> 
> typechecker@2.0.8 preinstall D:\Dev\docpad_test\Meny.docpad\node_modules\docpa
> d-plugin-text\node_modules\taskgroup\node_modules\ambi\node_modules\typechecker
> node ./cyclic.js

npm http 304 https://registry.npmjs.org/ansistyles

> safefs@3.0.4 preinstall D:\Dev\docpad_test\Meny.docpad\node_modules\docpad-plu
> gin-text\node_modules\bal-util\node_modules\safefs
> node ./cyclic.js

npm http 304 https://registry.npmjs.org/ansicolors
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/progress/1.1.2
npm http 304 https://registry.npmjs.org/read

> ambi@2.1.6 preinstall D:\Dev\docpad_test\Meny.docpad\node_modules\docpad-plugi
> n-text\node_modules\bal-util\node_modules\ambi
> node ./cyclic.js
> 
> typechecker@2.0.8 preinstall D:\Dev\docpad_test\Meny.docpad\node_modules\docpa
> d-plugin-text\node_modules\bal-util\node_modules\typechecker
> node ./cyclic.js

npm http 304 https://registry.npmjs.org/requirefresh
npm http 304 https://registry.npmjs.org/js2coffee
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/methods/0.0.1
npm http GET https://registry.npmjs.org/mute-stream

> typechecker@2.0.8 preinstall D:\Dev\docpad_test\Meny.docpad\node_modules\docpa
> d-plugin-partials\node_modules\taskgroup\node_modules\ambi\node_modules\typechec
> ker
> node ./cyclic.js

npm http 304 https://registry.npmjs.org/cookiejar/1.3.0
npm http 304 https://registry.npmjs.org/commander/1.3.2
npm http 304 https://registry.npmjs.org/mkdirp/0.3.5
npm http 304 https://registry.npmjs.org/range-parser/0.0.4
npm http 304 https://registry.npmjs.org/mime/1.2.5
npm http 304 https://registry.npmjs.org/emitter-component/1.0.0
npm http GET https://registry.npmjs.org/qs/0.5.1
npm http GET https://registry.npmjs.org/pause/0.0.1
npm http GET https://registry.npmjs.org/formidable/1.0.11
npm http GET https://registry.npmjs.org/cookie/0.0.4
npm http GET https://registry.npmjs.org/crc/0.2.0
npm http GET https://registry.npmjs.org/fresh/0.1.0
npm http GET https://registry.npmjs.org/bytes/0.1.0
npm http GET https://registry.npmjs.org/send/0.0.4
npm http 304 https://registry.npmjs.org/connect/2.11.0
npm http 304 https://registry.npmjs.org/cookie-signature/1.0.1

> js2coffee@0.2.3 preinstall D:\Dev\docpad_test\Meny.docpad\node_modules\docpad\
> node_modules\cson\node_modules\js2coffee
> node ./cyclic.js

npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/debuglog/0.0.2
npm http 304 https://registry.npmjs.org/qs/0.6.5
npm http 304 https://registry.npmjs.org/reduce-component/1.0.1
npm http GET https://registry.npmjs.org/tap
npm http GET https://registry.npmjs.org/file
npm http 304 https://registry.npmjs.org/buffer-crc32/0.2.1
npm http 304 https://registry.npmjs.org/fresh/0.2.0
npm http 304 https://registry.npmjs.org/cookie/0.1.0
npm http 304 https://registry.npmjs.org/methods/0.1.0
npm http 304 https://registry.npmjs.org/send/0.1.4
npm http 304 https://registry.npmjs.org/formidable/1.0.14
npm http 304 https://registry.npmjs.org/abbrev
npm http 304 https://registry.npmjs.org/argparse
npm http GET https://registry.npmjs.org/keypress
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/package
npm http 304 https://registry.npmjs.org/pkginfo
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/winston
npm http GET https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/cli/0.4.3
npm http 304 https://registry.npmjs.org/mute-stream
npm http GET https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/qs/0.5.1
npm http 304 https://registry.npmjs.org/pause/0.0.1
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/bytes/0.2.1
npm http 304 https://registry.npmjs.org/cookie/0.0.4
npm http 304 https://registry.npmjs.org/formidable/1.0.11
npm http GET https://registry.npmjs.org/multiparty/2.2.0
npm http GET https://registry.npmjs.org/raw-body/0.0.3
npm http GET https://registry.npmjs.org/negotiator/0.3.0
npm http GET https://registry.npmjs.org/uid2/0.0.3
npm http 304 https://registry.npmjs.org/crc/0.2.0
npm http GET https://registry.npmjs.org/eyes
npm http GET https://registry.npmjs.org/loggly
npm http GET https://registry.npmjs.org/stack-trace
npm http 304 https://registry.npmjs.org/fresh/0.1.0
npm http 304 https://registry.npmjs.org/bytes/0.1.0
npm http 304 https://registry.npmjs.org/send/0.0.4
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/debuglog/0.0.2
npm http 304 https://registry.npmjs.org/tap
npm http 304 https://registry.npmjs.org/file
npm http GET https://registry.npmjs.org/mime/1.2.6
npm http 304 https://registry.npmjs.org/keypress
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/runforcover
npm http GET https://registry.npmjs.org/slide
npm http GET https://registry.npmjs.org/difflet
npm http GET https://registry.npmjs.org/buffer-equal
npm http GET https://registry.npmjs.org/deep-equal
npm http 304 https://registry.npmjs.org/bytes/0.2.1
npm http 304 https://registry.npmjs.org/multiparty/2.2.0
npm http 304 https://registry.npmjs.org/raw-body/0.0.3
npm http 304 https://registry.npmjs.org/negotiator/0.3.0
npm http 304 https://registry.npmjs.org/uid2/0.0.3
npm http 304 https://registry.npmjs.org/eyes
npm http 304 https://registry.npmjs.org/loggly
npm http 304 https://registry.npmjs.org/stack-trace
npm http 304 https://registry.npmjs.org/mime/1.2.6
npm http 304 https://registry.npmjs.org/runforcover
npm http 304 https://registry.npmjs.org/slide
npm http 304 https://registry.npmjs.org/difflet
npm http 304 https://registry.npmjs.org/buffer-equal
npm http GET https://registry.npmjs.org/timespan
npm http GET https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/deep-equal
npm http GET https://registry.npmjs.org/bunker
npm http GET https://registry.npmjs.org/charm
npm http GET https://registry.npmjs.org/deep-is
npm http GET https://registry.npmjs.org/traverse
npm http GET https://registry.npmjs.org/stream-counter
npm http 304 https://registry.npmjs.org/timespan
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/bunker
npm http GET https://registry.npmjs.org/burrito
npm http 304 https://registry.npmjs.org/charm
npm http 304 https://registry.npmjs.org/deep-is
npm http 304 https://registry.npmjs.org/traverse
npm http 304 https://registry.npmjs.org/stream-counter
npm http 304 https://registry.npmjs.org/burrito
bal-util@1.15.4 node_modules\bal-util

underscore@1.4.4 node_modules\underscore

docpad-plugin-coffeescript@2.2.3 node_modules\docpad-plugin-coffeescript
└── coffee-script@1.6.3

docpad-plugin-marked@2.1.2 node_modules\docpad-plugin-marked
└── marked@0.2.10

grunt-css@0.3.2 node_modules\grunt-css
├── sqwish@0.2.0
├── csslint@0.9.9
└── gzip-js@0.3.1 (crc32@0.2.2, deflate-js@0.2.3)

docpad-plugin-eco@2.0.2 node_modules\docpad-plugin-eco
└── eco@1.1.0-rc-3 (strscan@1.0.1, coffee-script@1.6.3)

docpad-plugin-text@2.3.2 node_modules\docpad-plugin-text
├── taskgroup@3.3.1 (ambi@2.1.6)
└── bal-util@2.3.2 (extendr@2.1.0, eachr@2.0.2, extract-opts@2.2.0, safefs@3.0.4
, typechecker@2.0.8, ambi@2.1.6)

docpad-plugin-partials@2.8.1 node_modules\docpad-plugin-partials
├── extendr@2.1.0 (typechecker@2.0.8)
└── taskgroup@3.3.1 (ambi@2.1.6)

docpad-plugin-stylus@2.5.0 node_modules\docpad-plugin-stylus
├── stylus@0.38.0 (debug@0.7.3, mkdirp@0.3.5, cssom@0.2.5, sax@0.5.5)
└── nib@1.0.1 (stylus@0.35.1)

docpad@6.54.5 node_modules\docpad
├── lazy-require@1.0.0
├── extendr@2.1.0
├── eachr@2.0.2
├── extract-opts@2.2.0
├── caterpillar-filter@2.0.3
├── commander@2.0.0
├── envfile@1.0.0
├── getmac@1.0.6
├── event-emitter-grouped@2.3.2
├── ambi@2.1.6
├── mime@1.2.11
├── typechecker@2.0.8
├── safefs@3.0.4
├── query-engine@1.5.4
├── bal-util@2.3.2
├── taskgroup@3.3.1
├── safeps@2.2.9
├── backbone@1.1.0
├── semver@2.2.1
├── watchr@2.4.4 (taskgroup@3.2.4)
├── caterpillar-human@2.1.1 (ansistyles@0.1.1, ansicolors@0.2.1)
├── jschardet@1.1.0
├── progressbar@1.0.3 (progress@1.1.2)
├── lodash@2.2.1
├── encoding@0.1.7 (iconv-lite@0.2.11)
├── superagent@0.15.7 (methods@0.0.1, cookiejar@1.3.0, debug@0.7.3, qs@0.6.5, em
itter-component@1.0.0, reduce-component@1.0.1, mime@1.2.5, formidable@1.0.14)
├── promptly@0.2.0 (read@1.0.5)
├── caterpillar@2.0.6 (readable-stream@1.1.9)
├── cson@1.4.5 (requirefresh@1.1.2, coffee-script@1.6.3, js2coffee@0.2.3)
├── yamljs@0.1.4 (argparse@0.1.15, glob@3.1.21)
└── express@3.4.4 (methods@0.1.0, range-parser@0.0.4, cookie-signature@1.0.1, de
bug@0.7.3, fresh@0.2.0, buffer-crc32@0.2.1, cookie@0.1.0, send@0.1.4, mkdirp@0.3
.5, commander@1.3.2, connect@2.11.0)

grunt@0.3.17 node_modules\grunt
├── dateformat@1.0.2-1.2.3
├── colors@0.6.2
├── semver@1.0.14
├── async@0.1.22
├── hooker@0.2.3
├── underscore@1.2.4
├── underscore.string@2.1.1
├── gzip-js@0.3.2 (crc32@0.2.2, deflate-js@0.2.3)
├── uglify-js@1.3.5
├── nopt@1.0.10 (abbrev@1.0.4)
├── temporary@0.0.7 (package@1.0.1)
├── glob-whatev@0.1.8 (minimatch@0.2.12)
├── jshint@0.9.1 (minimatch@0.0.5, cli@0.4.3)
├── connect@2.4.6 (fresh@0.1.0, pause@0.0.1, debug@0.7.3, bytes@0.1.0, cookie@0.
0.4, crc@0.2.0, formidable@1.0.11, qs@0.5.1, send@0.0.4)
├── prompt@0.1.12 (pkginfo@0.3.0, winston@0.5.11)
└── nodeunit@0.7.4 (tap@0.4.4)

D:\Dev\docpad_test\Meny.docpad>docpad run
info: Welcome to DocPad v6.54.5 (local installation: D:\Dev\docpad_test\Meny.doc
pad\node_modules\docpad)
info: Contribute: http://docpad.org/docs/contribute
info: Plugins: coffeescript, eco, marked, partials, stylus, text
info: Environment: development
info: DocPad listening to http://localhost:9778/ on directory D:\Dev\docpad_test
\Meny.docpad\out
info: Generating...
error: Something went wrong with the action
error: An error occured:
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
info: Shutting down... cya next time!

D:\Dev\docpad_test\Meny.docpad>

**Comment by TravelingTechGuy** [comment]
This may be an issue with the way grunt is installed on Windows. You may need to install grunt-cli globally ('npm install -g grunt-cli'). Take a look at this DocPad issue and see if this solves it: https://github.com/bevry/docpad/issues/478

**Comment by andruhon** [comment]
Replacing 
<code>command = ["#{rootPath}/node_modules/.bin/grunt", 'default']</code>
to
<code>command = ['grunt.cmd', 'default']</code>
is working for me.

Thank you!

**Comment by TravelingTechGuy** [comment]
Cool! Thanks for the input.
