### ISSUE TITLE
Add the GitHub Topic: docpad-project

### ISSUE THREAD

**Issue by balupton** [TravelingTechGuy/Meny.docpad#2]
https://help.github.com/articles/about-topics/

**Comment by TravelingTechGuy** [comment]
Hi,
Not sure I understand what's needed?

**Comment by balupton** [comment]
to have this project show up on https://github.com/search?q=topic%3Adocpad-project the following needs to be done by you:

1. go to https://github.com/TravelingTechGuy/Meny.docpad
2. click the `Add Topics` button under the project description
3. Add the topic `docpad-project`
4. Click done
5. 🎉

**Comment by TravelingTechGuy** [comment]
🎉 indeed!
Cheers!

**Comment by balupton** [comment]
👌👏
